### ISSUE TITLE
Improve design of infobox for groups

### ISSUE THREAD

**Issue by gmazlami** [sebastian-stephan/groupfindr#10]
improve sizes, colors, buttons etc.

Group1: Title
 "Description of the group"
Members:
 1. member1
 2. member2
 3. member3

RED (X) for deleting for the group (larger)

**Comment by sebastian-stephan** [comment]
Looks a lot better now. Still not sure if we cannot improve this. When 30 people are connected it looks rather messy. Maybe we should make it more space efficient?
@scmo @gmazlami @benibl
