### ISSUE TITLE
Server validation when deleting groups

### ISSUE THREAD

**Issue by sebastian-stephan** [sebastian-stephan/groupfindr#14]
Rule that non-empty groups cannot be deleted is not enforced on server.

**Comment by Clabfabs** [comment]
Hey Sebi,

Wow... Merci viu mau für di effort..! hesch ja hurti e riese schub gmacht
letscht nacht.

I ha itz mini houpt-issues vom ASE-projekt meh oder weniger fertig u ga itz
no hingere groupfindr. Luege mau wi wit dasi hüt no chume.

Heit dir itz eigetlech was abgmacht für morn? Träffemer üs am morge eifach
no zum fertigmache?

Cheers,
Fabio

2015-05-27 17:58 GMT+02:00 Sebastian Stephan <notifications@github.com>:
